heat_template_version: 2015-10-15
description: >
  Creates all necessary configs and scripts for installing Heat Config Agents.

parameter_groups:

parameters:

resources:

  install_config_agent_rdo:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: { get_file: scripts/centos/os-collect-config/install_config_agent_rdo.sh }

  configure_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config:
        str_replace:
          params:
            $heat_config_script: { get_file: scripts/centos/os-collect-config/55-heat-config }
            $hook_script: { get_file: scripts/centos/os-collect-config/hook-script.py }
            $heat_config_notify: { get_file: scripts/centos/os-collect-config/heat-config-notify }
            $occ_conf: { get_file: scripts/centos/os-collect-config/os-collect-config.conf }
            $orc_oac: { get_file: scripts/centos/os-collect-config/20-os-apply-config }
          template: { get_file: scripts/centos/os-collect-config/configure_config_agent.sh }

  start_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: { get_file: scripts/centos/os-collect-config/start_config_agent.sh }

  install_config_agent:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: { get_resource: install_config_agent_rdo }
        - config: { get_resource: configure_config_agent }
        - config: { get_resource: start_config_agent }

outputs:

  config:
    value: { get_resource: install_config_agent }
