heat_template_version: 2015-04-30

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

resources:

  activate_nics:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/activate-nics.sh }

  deploy_activate_nics:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: activate_nics }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL

outputs:
