heat_template_version: 2015-04-30

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

  store_pass:
    type: string
    default: changeit
    hidden: true

  certificate:
    type: string

resources:

  keystore_add:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/java-keystore-add.sh }
      inputs:
        - name: http_proxy
        - name: https_proxy
        - name: no_proxy
        - name: STORE_PASS
        - name: CERTIFICATE

  deploy_keystore_add:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: keystore_add }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: https_proxy }
        no_proxy: { get_param: no_proxy }
        STORE_PASS: { get_param: store_pass }
        CERTIFICATE: { get_param: certificate }

outputs:
