heat_template_version: 2015-04-30

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

  device:
    type: string
    description: "The name of the block device"
    default: "/dev/vdb"

  mountpoint:
    type: string
    description: "The directory to mount the filesystem to."
    default: "/mnt"

  filesystem_type:
    type: string
    description: "The name of the filesystem to create on the disk"
    default: "ext4"

  filesystem_label:
    type: string
    description: "The label to set on the new filesystem"
    default: "volume"

  filesystem_options:
    type: string
    description: "Options to pass to mkfs"
    default: ""

resources:

  prepare_volume:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/prepare-volume.sh }
      inputs:
        - name: DEVICE
        - name: MOUNTPOINT
        - name: FILESYSTEM_TYPE
        - name: FILESYSTEM_LABEL
        - name: FILESYSTEM_OPTIONS

  deploy_prepare_volume:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: prepare_volume }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        DEVICE: { get_param: device }
        MOUNTPOINT: { get_param: mountpoint }
        FILESYSTEM_TYPE: { get_param: filesystem_type }
        FILESYSTEM_LABEL: { get_param: filesystem_label }
        FILESYSTEM_OPTIONS: { get_param: filesystem_options }

outputs:
