heat_template_version: 2015-04-30

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

  base_dir:
    type: string
 
  filename:
    type: string

  owner:
    type: string

  group:
    type: string

  file_perms:
    type: string

  dir_perms:
    type: string

  content:
    type: string

resources:

  copy-file:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/copy-file.sh }
      inputs:
        - name: BASE_DIR
        - name: FILENAME
        - name: OWNER
        - name: GROUP
        - name: PERMS
        - name: CONTENT

  deploy_copy_file:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: copy-file }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: https_proxy }
        no_proxy: { get_param: no_proxy }
        BASE_DIR: { get_param: base_dir }
        FILENAME: { get_param: filename }
        OWNER: { get_param: owner }
        GROUP: { get_param: group }
        DIR_PERMS: { get_param: dir_perms }
        FILE_PERMS: { get_param: file_perms }
        CONTENT: { get_param: content }

outputs:
